TRAINING_EXAMPLES = [
    ("Large pothole near Gate 2, several bikes almost fell.", "pothole"),
    ("Dangerous road hole outside Gate 2, very risky at night.", "pothole"),
    ("Huge pothole at the college main entrance, cars are swerving.", "pothole"),
    ("Deep pothole on the main road has been growing for weeks.", "pothole"),
    ("There is a big crater on the road near the bus stop.", "pothole"),
    ("Bike skidded because of a pothole outside the hostel gate.", "pothole"),
    ("Road has multiple potholes near the flyover, causing traffic.", "pothole"),
    ("A pothole filled with water is hidden and hard to see at night.", "pothole"),
    ("The pothole outside the market has damaged two auto-rickshaws.", "pothole"),
    ("Please fix the broken road surface, it's basically one big pit now.", "pothole"),
    ("Pothole near the traffic signal is causing two-wheelers to slip.", "pothole"),
    ("Road caved in after the rain, leaving a deep pothole.", "pothole"),
    ("The pothole near Gate 2 has still not been fixed, it's worse now.", "pothole"),
    ("Cracked and sunken tarmac near the roundabout, forms a pit.", "pothole"),
    ("Sharp-edged pothole on the service road hit my car's tyre.", "pothole"),
    ("Small pothole is expanding every day near the parking lot.", "pothole"),
    ("Garbage has not been collected for a week near our society gate.", "garbage"),
    ("Overflowing trash bin outside the market is attracting stray dogs.", "garbage"),
    ("Someone is dumping construction waste on the empty plot again.", "garbage"),
    ("The garbage truck skipped our street two days in a row.", "garbage"),
    ("Waste is piling up near the community bin and starting to smell.", "garbage"),
    ("Plastic waste is scattered all over the footpath near the park.", "garbage"),
    ("Dead animal lying near the garbage dump, needs urgent cleanup.", "garbage"),
    ("Household waste dumped illegally behind the library building.", "garbage"),
    ("Garbage bin near the bus stop is broken and trash spills onto the road.", "garbage"),
    ("Foul smell from uncollected garbage near the canteen area.", "garbage"),
    ("Trash has been burning in the open lot, causing smoke everywhere.", "garbage"),
    ("The dustbin outside our building has not been emptied in days.", "garbage"),
    ("Litter and food waste accumulating outside the hostel mess.", "garbage"),
    ("Someone dumped a mattress and old furniture on the roadside.", "garbage"),
    ("Rag pickers scattered the sorted garbage all over the lane.", "garbage"),
    ("Streetlight outside our building has been off for ten days.", "streetlight"),
    ("The whole street near the park is dark, all lights are out.", "streetlight"),
    ("Street lamp near the college gate is flickering and about to die.", "streetlight"),
    ("No lighting on the road behind the library, feels unsafe at night.", "streetlight"),
    ("Streetlight pole is damaged and leaning dangerously towards the road.", "streetlight"),
    ("Several streetlights near the roundabout are not working.", "streetlight"),
    ("The lamp post near the bus stop has been broken for a month.", "streetlight"),
    ("It's pitch dark near the parking area because the light is fused.", "streetlight"),
    ("Streetlight wiring is exposed and sparking near the footpath.", "streetlight"),
    ("Light near Gate 3 keeps switching on and off randomly.", "streetlight"),
    ("The entire lane has no functioning streetlights since the storm.", "streetlight"),
    ("Street lamp glass is broken and the bulb is hanging out.", "streetlight"),
    ("Dark stretch of road near the underpass has no working lights.", "streetlight"),
    ("Streetlight outside the temple has not worked since last month.", "streetlight"),
    ("Drainage near the market is blocked and water is flooding the road.", "drainage"),
    ("Open drain outside our house is overflowing with dirty water.", "drainage"),
    ("Sewage is backing up onto the street after every rain.", "drainage"),
    ("The stormwater drain is clogged with plastic and leaves.", "drainage"),
    ("Manhole cover is missing near the drain, it's a serious hazard.", "drainage"),
    ("Water is stagnant in the drain near the park, mosquitoes breeding.", "drainage"),
    ("Drain pipe burst near the hostel and water is spreading on the road.", "drainage"),
    ("Blocked culvert is causing water to pool outside the college gate.", "drainage"),
    ("Sewage smell near the drainage line behind the canteen is unbearable.", "drainage"),
    ("The drain near Gate 2 has been overflowing since the last storm.", "drainage"),
    ("Choked drainage is causing waterlogging every time it rains.", "drainage"),
    ("Broken drain cover near the footpath is a tripping hazard.", "drainage"),
    ("Dirty water from the drain is seeping into the ground floor shops.", "drainage"),
    ("The footpath tiles near the park are broken and uneven.", "road_infrastructure"),
    ("Road divider near the signal is damaged after an accident.", "road_infrastructure"),
    ("Bus shelter roof has collapsed partially near the main stop.", "road_infrastructure"),
    ("Guard rail on the flyover is bent and needs urgent repair.", "road_infrastructure"),
    ("Footbridge near the station has a broken railing, unsafe to cross.", "road_infrastructure"),
    ("Speed breaker near the school is too high and damaging vehicles.", "road_infrastructure"),
    ("Road signage near the junction has fallen down and is missing.", "road_infrastructure"),
    ("Zebra crossing paint has completely faded near the main gate.", "road_infrastructure"),
    ("Footpath near the college is blocked by construction debris.", "road_infrastructure"),
    ("The compound wall near the park has cracked and could collapse.", "road_infrastructure"),
    ("Traffic signal at the junction has been malfunctioning all week.", "road_infrastructure"),
    ("Railing along the bridge is broken in several places.", "road_infrastructure"),
    ("No water supply in our area for the third day in a row.", "water_supply"),
    ("Water pipeline burst near the main road, wasting thousands of litres.", "water_supply"),
    ("Muddy, discoloured water is coming from the tap since morning.", "water_supply"),
    ("Water tanker did not arrive on the scheduled day again.", "water_supply"),
    ("Low water pressure across the entire street for over a week.", "water_supply"),
    ("Leaking water pipe near the footpath is flooding the lane.", "water_supply"),
    ("Water supply timing has been irregular for the whole month.", "water_supply"),
    ("Contaminated water smell coming from the tap, unsafe to drink.", "water_supply"),
    ("Underground pipeline leak is causing a sinkhole near the market.", "water_supply"),
]
